version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fake-review-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./nginx
    container_name: fake-review-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
